apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
  namespace: laravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      containers:
      - name: laravel-app
        image: <DOCKERHUB_USER>/laravel-cicd-app:latest
        ports:
        - containerPort: 9000
        env:
        - name: DB_HOST
          value: mysql
        - name: DB_DATABASE
          value: laravel
        - name: DB_USERNAME
          value: laravel
        - name: DB_PASSWORD
          value: secret
