apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel-app
  namespace: laravel-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: laravel-app
  template:
    metadata:
      labels:
        app: laravel-app
    spec:
      containers:
        - name: laravel-app
          image: zubairalamdev/laravel-app:build-25
          ports:
            - containerPort: 9000
          envFrom:
            - secretRef:
                name: laravel-env   # your Laravel .env (stored as a K8s Secret)
